sudo: required
language: java

jdk:
  - oraclejdk8

before_install:
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis CI"

script: "mvn test && mvn clean package"

branches:
  only: 'master'

cache:
  directories:
    - '$HOME/.m2/repository'