name: ${project.name}
main: org.js.faucet.FaucetJS
version: ${project.version}
authors: [Aerh, LamboCreeper, TheMasteredPanda]
website: https://faucet.js.org/
commands:
  faucet:
    description: The main command for faucet.js
    usage: /faucet
